### ISSUE TITLE
Github link on topcoat.io should link to github.com/topcoat/topcoat

### ISSUE THREAD

**Issue by kristoferjoseph** [topcoat/topcoat#446]
Currently the github link in the footer of topcoat.io links to github.com/topcoat which drops you into the list of all the repos. We should instead drop you into github.com/topcoat/topcoat so users can see the README.

**Comment by marnen** [comment]
I just submitted topcoat/topcoat.github.com#33, which fixes this.

**Comment by marnen** [comment]
...and in 7 months, no one has done anything about it.
