### ISSUE TITLE
Placeholders inputs not centered with Android 4.1.2

### ISSUE THREAD

**Issue by matthieuh** [topcoat/topcoat#453]
Hi, I have a problem with placeholders inputs in mobile theme of topcoat v0.8.0 when testing on a android phone in version 4.1.2. Placeholders are not centered. The problem affect just placeholder not value like you can see in screenshots. With a computer browser i haven't the problem.

![placeholder-pb](https://f.cloud.github.com/assets/1550192/1571002/761d3336-50fa-11e3-903c-d31ba29bbbfc.jpg)
![screenshot_2013-11-19-10-00-27](https://f.cloud.github.com/assets/1550192/1571003/784b0610-50fa-11e3-8aeb-0b087e4fccd9.png)

**Comment by GarthDB** [comment]
We are cleaning up and getting ready for a new start on Topcoat from a team within Adobe. The next release has a new design and will start from an orphaned branch, so none of this will still exist.
