### ISSUE TITLE
radio button z-index issue

### ISSUE THREAD

**Issue by kof** [topcoat/topcoat#465]
Hi,

I have spent some hours to find out why ... but no luck :) z-index: 2 is required in my case to let radio buttons be checkable by clicking the button itself.

.radio-button:before,
.radio-button:after,
.topcoat-radio-button__checkmark:before,
.topcoat-radio-button__checkmark:after {
  content: '';
  position: absolute;
  border-radius: 100%;
  z-index: 2;
}

It seems like input field is overlapping the checkmark element and so makes it unreachable. Its not a specific browser issue, because examples work just fine in the same browser. (latest chrome on mac)

Actually the question is why does it work in the examples if checkmark has a lower z-index than input.

I went all the css properties through and couldn't find anything I have redefined, everything comes from topcoat.

**Comment by GarthDB** [comment]
We are cleaning up and getting ready for a new start on Topcoat from a team within Adobe; we'll have to do some more browser testing as part of that.
