### ISSUE TITLE
Search input in Firefox [0.9]

### ISSUE THREAD

**Issue by piatra** [topcoat/topcoat#480]
This is how search input looks for me in FF 
![screenshot from 2014-02-09 12 10 08](https://f.cloud.github.com/assets/810040/2119531/606bef6a-9172-11e3-95f2-2c325ac8ff5c.png)

Firefox and Chrome seem to interpret background-position values (in rems) differently. Using pixels renders the same in both browsers.

**Comment by GarthDB** [comment]
We are cleaning up and getting ready for a new start on Topcoat from a team within Adobe. We'll have to start from scratch on this with the new release.
