### ISSUE TITLE
Font not rendering on Topcoat.io

### ISSUE THREAD

**Issue by nnnnic** [topcoat/topcoat#481]
See attached:
![screen shot 2014-02-10 at 11 02 27 am](https://f.cloud.github.com/assets/997862/2130748/b91d057a-9296-11e3-96bd-d2f6c6ca9c03.png)

Possible related to https://github.com/topcoat/topcoat/issues/452 ?

**Comment by GarthDB** [comment]
Thanks @nnnnic - we're clearing it all out and will have to start from scratch in the next release.
