### ISSUE TITLE
All buttons in navigation bar should have vertical-align: baseline

### ISSUE THREAD

**Issue by arnemart** [topcoat/topcoat#485]
The following code:

``` html
<div class="topcoat-navigation-bar">
    <div class="topcoat-navigation-bar__item left quarter">
        <button class="topcoat-icon-button">
            <span class="topcoat-icon topcoat-icon--menu-stack"></span>
        </button>
    </div>
    <div class="topcoat-navigation-bar__item center half">
        <h1 class="topcoat-navigation-bar__title">Hello</h1>
    </div>
    <div class="topcoat-navigation-bar__item right quarter">
        <button class="topcoat-button">Button</button>
    </div>
</div>
```

renders like this:

![screen shot 2014-02-26 at 09 58 05](https://f.cloud.github.com/assets/662021/2268117/7471b684-9ec4-11e3-9865-a7f727a0d951.png)

When the normal button (on the right) is given `vertical-align: baseline`, it lines up correctly just like the icon button. Maybe all buttons inside navigation bars should have `vertical-align: baseline`? Or are you not supposed to use normal buttons in navigation bars?

**Comment by GarthDB** [comment]
We are cleaning up and getting ready for a new start on Topcoat from a team within Adobe. This will be addressed with the next release.
