### ISSUE TITLE
Placeholder on Cordova 3.1/Android 4+ fails

### ISSUE THREAD

**Issue by matejsvajger** [topcoat/topcoat#491]
line-height on input fields messes up the placeholder and it keeps it at the top of the input field. Removing the line-height on .topcoat-search-input and substituting it with height fixed the problem on phonegap/android app.

**Comment by GarthDB** [comment]
We are cleaning up and getting ready for a new start on Topcoat from a team within Adobe. We'll have to address this with the new release.
