### ISSUE TITLE
:hover on touch devices

### ISSUE THREAD

**Issue by kof** [topcoat/topcoat#493]
There is actually no such a thing there, as there is no pointer. It leads to persistent :hover state after interaction is done.

I have fixed this for now by removing :hover selectors/rules at runtime https://github.com/kof/remove-hover

mostly because I don't want to modify topcoat for this.

Ideally, mobile only build should not contain :hover declarations or it should be configurable via css ....

**Comment by GarthDB** [comment]
We are cleaning up and getting ready for a new start on Topcoat from a team within Adobe. We should be able to make a way to bring back the hover classes if needed.
