### ISSUE TITLE
Benchmarks don't work in Chrome OSX?

### ISSUE THREAD

**Issue by jemminger** [topcoat/topcoat#500]
It doesn't look like your benchmarks are working in Chrome on OSX:

![screen shot 2015-04-17 at 9 03 55 pm](https://cloud.githubusercontent.com/assets/2272/7213240/6265e7da-e545-11e4-86a0-d8650f3a15d5.png)

**Comment by kristoferjoseph** [comment]
Adobe took down the amazon servers.

**Comment by jemminger** [comment]
So, the benchmarks are expected not to work anymore?

**Comment by kristoferjoseph** [comment]
That is not the way I would

**Comment by GarthDB** [comment]
We are cleaning up and getting ready for a new start on Topcoat from a team within Adobe. This will be addressed with the next release.
