### ISSUE TITLE
Identify supported browsers

### ISSUE THREAD

**Issue by AllThingsSmitty** [topcoat/topcoat#504]
Merged PR https://github.com/topcoat/topcoat/pull/499 outlines supported browsers configured for Autoprefixer: `browsers: ['last 2 versions', 'ie >= 8', '> 1%']`. This should cover the basics:
- Chrome (latest 2)
- Edge (latest 2)
- Firefox (latest 2)
- Internet Explorer 8+
- Opera (latest 2)
- Safari (latest 2)

If agreed on, we should add this to the README.

**Comment by AllThingsSmitty** [comment]
Submitted PR https://github.com/topcoat/topcoat/pull/505.

**Comment by GarthDB** [comment]
We should add it to the README.
We are cleaning things up and getting ready for a new start on Topcoat from a team within Adobe; we should make sure to add it to the next release.
