### ISSUE TITLE
http://bench.topcoat.io is 404

### ISSUE THREAD

**Issue by zhaoyou** [topcoat/topcoat#512]
This url can't open.

**Comment by piatra** [comment]
The website is down because the testing infrastructure isn't in place anymore. It will return.

**Comment by GarthDB** [comment]
Hey @piatra do you want to chat sometime about getting it back? I could probably get budget to get a mac mini to set it up with a nexus I have around.

**Comment by piatra** [comment]
@GarthDB hey! Sure thing! Feel free to hit me up on hangouts or Twitter DMs.
