### ISSUE TITLE
Is this project still viable?

### ISSUE THREAD

**Issue by metaloha** [topcoat/topcoat#513]
Looks like it hasn't been updated for some time now, just wondering if there is still progress towards v1.0.0

**Comment by GarthDB** [comment]
Hey @metaloha sorry for the delay.

Topcoat is viable and I'm making progress. It is currently just me, so if you would like to contribute I would be happy to have any help.

**Comment by abrander** [comment]
For anyone else coming here for signs of life - the 1.0 branch seems to be alive!

https://github.com/topcoat/topcoat/tree/1.0.0

**Comment by GarthDB** [comment]
Lots of progress - will write on the blog about it as I get more parts working together.
